# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'category.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog, listValues):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 50, 291, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.txtCategoryID = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtCategoryID.setReadOnly(True)
        self.txtCategoryID.setObjectName("txtCategoryID")
        self.gridLayout.addWidget(self.txtCategoryID, 0, 1, 1, 1)
        self.lblCategoryID = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblCategoryID.setObjectName("lblCategoryID")
        self.gridLayout.addWidget(self.lblCategoryID, 0, 0, 1, 1)
        self.lblCategory = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblCategory.setObjectName("lblCategory")
        self.gridLayout.addWidget(self.lblCategory, 1, 0, 1, 1)
        self.txtCategory = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtCategory.setObjectName("txtCategory")
        self.gridLayout.addWidget(self.txtCategory, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(210, 250, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.Dialog = Dialog
        self.listValues = listValues
        self.initialSetup()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblCategoryID.setText(_translate("Dialog", "Categories ID"))
        self.lblCategory.setText(_translate("Dialog", "Categories"))





########################################################################
#                                                                      #
#                           Events                                     #
#                                                                      #
########################################################################

    def initialSetup(self):
        self.setValues()



    def setValues(self):
        if self.listValues == None:
            return
        self.txtCategoryID.setText(str(self.listValues[0]))
        self.txtCategory.setText(self.listValues[1])


#####################################################################
# use getEditValues when edit the categories
# use getValues when add the new categories

    def getValues(self):
        listResult = []
        listResult.append(self.txtCategoryID.text())
        listResult.append(self.txtCategory.text())
        return listResult




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, None)
    Dialog.show()
    sys.exit(app.exec_())
